lesson-26
Ibadichan/Question-Answer pull request #3
Opened 2017-06-26 20:35 UTC by Ibadichan

2017-06-27 06:27 UTC, iBublik requested changes

2017-06-27 06:27 UTC, iBublik commented on app/controllers/questions/answers_controller.rb
> +class Questions::AnswersController < ApplicationController
Не вижу смысла вкладывать контроллер вопросов в неймспейс questions

2017-06-27 06:27 UTC, iBublik commented on app/controllers/questions/answers_controller.rb
> +      redirect_to @question, alert: 'Ваш ответ не создан'
При редиректе все ошибки потеряются. Нужно делать render, чтоб отобразить ошибки

2017-06-27 06:27 UTC, iBublik commented on app/controllers/questions/answers_controller.rb
> +  def destroy
По условиям задачи только автор может удалять свой ответ

2017-06-27 06:27 UTC, iBublik commented on app/controllers/questions_controller.rb
> +  def destroy
По условиям задачи только автор может удалять свой вопрос

2017-06-27 06:27 UTC, iBublik commented on app/views/questions/show.html.slim
> +  - if current_user == @question.user
А если пользователь не авторизован?

2017-06-27 06:27 UTC, iBublik commented on app/views/questions/show.html.slim
> +  - if current_user == @question.user
Рекомендую эту проверку вынести в модель пользователя. Тогда везде можно будет писать `current_user.author_of?(@question)` или `current_user.author_of?(@answer)`. И проверку в этом методе делай по id, а не по инстансам моделей - это быстрее работает

2017-06-27 06:27 UTC, iBublik commented on app/views/questions/show.html.slim
> +  - @question.answers.each_with_index do |answer, i|
`each.with_index(1)` - позволит убрать `i + 1`

2017-06-27 06:27 UTC, iBublik commented on db/migrate/20170626081226_add_user_id_to_questions.rb
> +    add_belongs_to :questions, :user, index: true
В 5 рельсах индекс для связей создается по умолчанию, а вот внешний ключ нужно добавить - контроль целостности на уровне БД хорошая штука.

2017-06-27 06:27 UTC, iBublik commented on db/migrate/20170626131224_add_user_id_to_answers.rb
> +    add_belongs_to :answers, :user, index: true
Аналогично вопросам - нужен внешний ключ

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/answers/create_answer_spec.rb
> +  before {question}
В приемочных тестах принято использовать `background` вместо `before`. Это синонимы, но терминология ближе к "пользовательской".
А еще, чтоб не делать такого вручную, можно использовать бэнг версию хелперов `let/given` - `let!/given!`. Они гарантируют, что на начало выполнения тестов код хелпера будет выполнен. В данном случае вопрос будет создан на начало теста.

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/answers/create_answer_spec.rb
> +feature 'user creates answer', %q{
В данной фиче лучше сразу заходить на страницу вопроса `visit question_path(question)`. А для проверки списка вопросов нужен отдельный тест

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/answers/create_answer_spec.rb
> +    expect(page).to have_content 'Ответ успешно создан'
Нужно еще проверить, что на странице появилось тело созданного ответа

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/answers/create_answer_spec.rb
> +
Нужен тест с попыткой создания невалидного ответа. В нем надо проверить вывод ошибки на странице

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/answers/delete_answer_spec.rb
> +    question
Вопрос итак создастся при создании ответа

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/answers/delete_answer_spec.rb
> +    answer
Вот тут как раз `given!` подойдет

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/answers/delete_answer_spec.rb
> +  given(:user2) {create(:user)}
Используй более понятные имена - `author, non-author`. Иначе очень сложно в тесте разобрать с каким контекстом ты работаешь

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/answers/delete_answer_spec.rb
> +    expect(page).to have_no_content 'Удалить ответ'
Лучше более точно указывать какого жлемента не должно быть - `to have_no_link`, `to have_no_button` и т.д. `have_no_content` используй только если просто текст проверяешь

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/questions/all_questions_spec.rb
> +  scenario 'User tries to see all questions' do
Тут нужно два сценария - для авторизованного и не авторизованного юзера

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/questions/all_questions_spec.rb
> +  scenario 'User tries to see all questions' do
И где проверка что на странице есть список вопросов с ссылками на них?

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/questions/create_question_spec.rb
> +
Нужен сценарий с созданием невалидного вопроса

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/questions/delete_question_spec.rb
> +feature 'User deletes question', %q{
Переходи сразу на страницу вопроса, мы ведь его удаление проверяем

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/questions/delete_question_spec.rb
> +    expect(page).to have_content 'Вопрос удален'
Нужно проверить, что на странице больше нет заголовка вопроса

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/users/log_out_spec.rb
> +    expect(current_path).to eq root_path
Нужно проверить, что вывелось сообщение об успешном выходе из системы

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/users/log_out_spec.rb
> +
Нужен сценарий с проверкой, что незалогиненный юзер не видит кнопки "Выйти"

2017-06-27 06:27 UTC, iBublik commented on spec/acceptance/users/registration_spec.rb
> +
Нужно проверить, что залогиненный юзер не видит кнопки регистрации

2017-06-27 06:27 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
>        it 'saves the answer in the database' do
Нужен тест для проверки привязки ответа в пользователю

2017-06-27 06:27 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Нужен контекст с попыткой удаления чужого ответа

2017-06-27 06:27 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
>          expect { post :create, params: { question: attributes_for(:question) } }.to change(Question, :count).by(1)
В этом тесте нужно проверить, что вопрос связался с текущим пользователем (делай через ассоциацию)

2017-06-27 06:27 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +    sign_in_user
Нужен контекст с попыткой удаления чужого вопроса

2017-06-27 06:27 UTC, iBublik commented on spec/factories/answers.rb
>      body  'MyText'
Для проверки списка ответов нужно обеспечить уникальность тела каждого ответа. Используй последовательности

2017-06-27 06:27 UTC, iBublik commented on spec/factories/questions.rb
>      title 'MyString'
Для проверки списка вопросов нужно обеспечить уникальность текста каждого вопроса. Используй последовательности

2017-06-27 06:27 UTC, iBublik commented on spec/rails_helper.rb
> +  config.include AcceptanceHelpers, type: :feature
Не хватает теста с просмотром страницы вопроса. Там нужно проверить отображение списка ответов к нему

2017-06-28 06:12 UTC, iBublik commented on app/controllers/questions/answers_controller.rb
> +class Questions::AnswersController < ApplicationController
И все же, зачем эта вложенность?

2017-06-28 06:12 UTC, iBublik commented on app/views/questions/show.html.slim
> +  - if current_user == @question.user
См. мои комментарии выше

2017-06-28 06:12 UTC, iBublik commented on spec/acceptance/answers/create_answer_spec.rb
> +  given!(:question) { create(:question) }
Бэнг методы тут избыточны

2017-06-28 06:12 UTC, iBublik commented on spec/acceptance/answers/delete_answer_spec.rb
> +    expect(page).to have_content 'Ваш ответ удален'
Нужно проверить, что контент ответа пропал со страницы

2017-06-28 06:12 UTC, iBublik commented on spec/acceptance/questions/all_questions_spec.rb
> +  given!(:question) { create(:question) }
Тут надо создать и проверить именно список, ведь на индекс странице мы отображаем все вопросы

2017-06-28 06:12 UTC, iBublik commented on spec/acceptance/questions/delete_question_spec.rb
> +  given(:user2) { create(:user) }
Рекомендация по понятности нейминга относится ко всем тестам

2017-06-28 06:12 UTC, iBublik commented on spec/acceptance/questions/delete_question_spec.rb
> +  before { question }
Зачем? При переходе на страницу вопроса (`visit question_path(question)`) вопрос итак создастся

2017-06-28 06:12 UTC, iBublik commented on spec/acceptance/answers/delete_answer_spec.rb
> +    expect(page).to have_no_link 'Удалить ответ'
Здесь поправил, а тестом выше все по-прежнему :) я не могу писать замечания к каждой строке, их итак много - так что применяй рекомендации ко всем подобным случаям

2017-06-28 06:12 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question) } }.to change(@user.questions, :count).by(1)
Теперь тест строкой выше становится избыточным. В этом мы проверили и создание вопроса, и его привязку к пользователю

2017-06-28 06:12 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +        question_of_user
Когда пишешь подобный код (вызов хелпера для того чтоб выполнился его код), значит нужен бэнг-метод (`let!`)

2017-06-28 06:12 UTC, iBublik commented on spec/factories/answers.rb
> +      user
А зачем в невалидном ответе нам создавать юзера и вопрос? Лучше сэкономить и сделать эти поля пустыми (nil), раз объект все равно не валиден

2017-06-28 06:12 UTC, iBublik commented on spec/support/acceptance-helpers.rb
> +  def show_question(question)
Слишком специфичный метод, чтоб выносить его в общие хелперы. Он нужен для одного теста

2017-06-28 06:12 UTC, iBublik commented on spec/models/user_spec.rb
> +        expect(author.author_of?(question)).to be true
rspec делает динамические метчеры (методы для проверки) для методов-предикатов (это методы, которые заканчиваются на знак вопроса и возвращают true/false) и можно писать короче и красивее:
expect(user).to be_author_of(answer)
т.е. название метчера получается из названия метода без вопр. знака и с доавлением be_ в начале

2017-06-28 06:12 UTC, iBublik commented on spec/models/user_spec.rb
> +        expect(author.author_of?(answer)).to be true
Достаточно проверки для вопроса. Когда у нас в системе появятся другие сущности, не будешь же ты для каждой писать отдельную проверку

2017-06-28 07:42 UTC, vkurennov requested changes

2017-06-28 07:42 UTC, vkurennov commented on app/controllers/questions/answers_controller.rb
> +class Questions::AnswersController < ApplicationController
Под вложенным ресурсом подразумевается вложенность на уровне роутов, а не на уровне неймспейсов. Контроллеры вкладываются в неймспейсы, если это какие-то отдельные части приложения, как, например, админка и основной сайт. Здесь это не нужно и только усложняет код и роутинг. Исправь

2017-06-28 07:42 UTC, vkurennov commented on app/controllers/questions/answers_controller.rb
> +      @question.reload
Зачем тут reload?

2017-06-28 07:42 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if current_user == @question.user
Да, замени на вызов `User#author_of?`

2017-06-28 07:42 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        - if user_signed_in?
Вместо вложенного условия можно использовать составное, а еще лучше - оператор safe navigation из руби 2.3 и выше.

2017-06-28 07:42 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +  given!(:question) { create(:question) }
Можно оставить, для уверенности, что данные точно созданы до теста

2017-06-28 07:42 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +    expect(page).to have_content 'Ваш ответ удален'
Да, нужно проверить, что овтета нет на странице

2017-06-28 07:42 UTC, vkurennov commented on spec/acceptance/questions/all_questions_spec.rb
> +  given!(:question) { create(:question) }
Да, нужен список, причем разных вопросов (используй sequence в фабриках для этого)

2017-06-28 07:42 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question) } }.to change(@user.questions, :count).by(1)
Да, достаточно только этого теста, он проверяет все, что нужно

2017-06-29 05:20 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      # не надо, если есть другое решение подскажите пожалуйста.
Во вьюхе надо рендерить только сохраненные (`persisted?`) ответы

2017-06-29 05:20 UTC, iBublik commented on app/views/questions/new.html.slim
> +  = f.label :title, t('questions.new.title')
Можно перевести атрибуты AR модели, тогда в лейблы они автоматом попадут. Пересмотри скринкаст по локалям из базового курса

2017-06-29 05:20 UTC, iBublik commented on app/views/questions/new.html.slim
> +  = f.submit t('questions.new.action', action: @question.new_record? ? 'Создать' : 'Изменить')
Сокращенная форма записи `t('.action')` - локали будут искать относительно текущего пути к вьюхе (как раз `questions.new`)

2017-06-29 05:20 UTC, iBublik commented on app/views/questions/show.html.slim
> +  - if user_signed_in? && current_user.author_of?(@question)
В Ruby 2.3 появился safe navigaton operator `&` - позволяет избежать проверки на `nil`. В данном случае можно заменить на `if current_user&.author_of?(@question)`

2017-06-29 08:29 UTC, vkurennov approved these changes

2017-06-29 08:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render 'common/errors', resource: @answer
Думаю, это можно вызов паршал ошибок поместить в паршл формы ответа

2017-06-29 08:42 UTC, merged