lesson-28
Ibadichan/Question-Answer pull request #6
Opened 2017-07-03 19:34 UTC by Ibadichan

2017-07-10 19:02 UTC, iBublik requested changes

2017-07-10 19:02 UTC, iBublik commented on .rubocop.yml
> +  Max: 20
Зачем так много? :)

2017-07-10 19:02 UTC, iBublik commented on app/assets/javascripts/answers.js.coffee
> +    answer_id =  $(this).parents('.answer-wrapper').data('answerId');
В JS принято использовать camelCase (`answerId`)

2017-07-10 19:02 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    return unless current_user.author_of?(@answer)
Можно вынести в before_action для экшенов destroy, update и best. И возвращать `head :forbidden` - это заголовок с кодом ответа 403 (как раз означает что нет прав для совершения действия)

2017-07-10 19:02 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @question.answers.update_all(best: false)
Всю логику установки лучшего ответа нужно вынести в модель - ей не место в контроллере. Все действия надо завернуть в транзакцию, если одно из них провалится, то откатятся все разом. Но транзакция откатывается только если было выброшено исключение, так что использую бэнг версию для обновления ответа (`update!`)

2017-07-10 19:02 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :best)
А зачем в параметрах `best`?

2017-07-10 19:02 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    @question.update(question_params) if current_user.author_of?(@question)
Тут тоже можно `head :forbidden` возвращать для не авторов. Это более правильно, чем молча рендерить вьюху

2017-07-10 19:02 UTC, iBublik commented on app/views/answers/best.js.erb
> +$('.answers').html('<%= j render @question.answers.by_best %>');
Можно не перерисовывать весь список - это избыточно. Просто перемести новый лучший ответ в верх списка, добавь ему бейдж, скрой ссылку. А у старого лучшего надо убрать бейдж и показать ссылку.

2017-07-10 19:02 UTC, iBublik commented on app/views/answers/update.js.erb
> +  $('.answers').html('<%= j render @question.answers %>');
А зачем заново весь список рендерить? Просто добавь новый ответ в конец списка

2017-07-10 19:02 UTC, iBublik commented on app/views/questions/_edit.html.slim
> +  = form_for @question, remote: true do |f|
В партиалы все переменные лучше передавать явно. Иначе ты потом запубешь что-то передать, партиал в тихую отрендерится и будет падать со странными ошибками. Т.е. используй тут локальные переменные и передавай данные при вызове явно: `render 'edit', question: @question` (даже rails так делает в анонимных партиалах)

2017-07-10 19:02 UTC, iBublik commented on app/views/questions/update.js.erb
> +  $('.question-wrapper').html('<%= j render @question %> <%= j render 'edit'%>');
А зачем 2 рендера? Лучше менять только сам вопрос, форму не трогай

2017-07-10 19:02 UTC, iBublik commented on spec/acceptance/answers/best_answer_spec.rb
> +    background do
Куда же так много действий в `background`? Логика теста должна быть описана в тесте, а тут только подготовительные действия (залогиниться, зайти на страничку вопроса).

2017-07-10 19:02 UTC, iBublik commented on spec/acceptance/answers/best_answer_spec.rb
> +        expect(page).to have_content answers.last.body
Ассерт в `background` - это уже запашок

2017-07-10 19:02 UTC, iBublik commented on spec/acceptance/answers/best_answer_spec.rb
> +    scenario 'author tries to select best answer', js: true do
Пустой тест - это сигнал о том что в `before` сделано слишком много

2017-07-10 19:02 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @question.answers.update_all(best: false)
И протестировать этот метод не забудь

2017-07-10 19:02 UTC, iBublik commented on spec/acceptance/answers/best_answer_spec.rb
> +    scenario 'author tries to re-select best answer', js: true do
Я не понимаю разницу между этим тестом и тем что выше. Если проверяешь смену лучшего ответа, то не надо ориентироваться на first/last элемент коллекции. Надо явно задавать лучший ответ (через отдельную фабрику, чтоб инкапсулировать логику хранения лучшего ответа в нее), потом проверять что он больше не первый в списке и что у него нет бейджа "Лучший"

2017-07-10 19:02 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        expect(answer_of_question.best).to eq true
`expect(answer_of_question).to be_best` - не забывай про матчеры для предикатов, которые генерирует rspec

2017-07-10 19:02 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        expect(answer.best).to eq false
Тут тоже надо `reload` делать, без этого ответ в памяти никак не узнает об изменениях. И можно так записать:
`expect { patch :best, params: { id: answer, format: :js } }.to_not change { answer.reload.best }`

2017-07-10 19:02 UTC, iBublik commented on spec/factories/answers.rb
> +    best false
Это не обязательно прописывать, Rails умеет подставлять дефолтные значения указанные в миграции

2017-07-10 19:02 UTC, iBublik commented on spec/models/answer_spec.rb
> +  describe '.by_best' do
Чтоб подчеркнуть, что это тест скоупа, а не просто метода класса, можно обернуть в `describe 'scopes'`

2017-07-10 19:02 UTC, iBublik commented on spec/models/answer_spec.rb
> +      answers << best_answer
А это зачем делать? Чтоб на начало теста данные проинициализировать, нужно бэнг-методы использовать (`let!(:answers) { ... }`)

2017-07-12 06:35 UTC, iBublik requested changes

2017-07-12 06:35 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  before_action :authorship, only: %i[destroy update]
Заметь что все before_action кроме этого имеют глагол в имени. Потому что действие должно содержать глагол :) Замени на check_authorship или authorize

2017-07-12 06:35 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    return head :forbidden unless current_user.author_of?(@answer)
return не нужен, метод итак возвращает последнее вычисленное выражение

2017-07-12 06:35 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    # здесь не вынес в before так как здесь я проверяю вопрос а не ответ
Этот комментарий можно убрать :)

2017-07-12 06:35 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    render :delete
Почему просто не назвать шаблон `destroy.js.erb`? Тогда не придется явно указывать имя шаблона, рельса сама догадается

2017-07-12 06:35 UTC, iBublik commented on app/views/answers/best.js.erb
> +var newLinkBestAnswer = newBestAnswer.find('a[href="/answers/<%= @answer.id %>/best"]');
Так может ссылке задать какой-нибудь класс или id, чтоб не таким сложным способом искать?

2017-07-12 06:35 UTC, iBublik commented on app/views/answers/best.js.erb
> +$('.answers div:first-child').before(newBestAnswer);
`before` не делает ничего, он просто возвращает элемент перед указанным селектором

2017-07-12 06:35 UTC, iBublik commented on app/views/answers/best.js.erb
> +// а вначале был такой короткий код ....
Да, получилось жутковато. Лучше вернуть рендеринг всего списка, чем такое оставлять :)

2017-07-12 06:35 UTC, iBublik commented on app/views/answers/update.js.erb
> +  $('.answers').append('<%= j render @answer %>');
Да, тут я перепутал с create. Правильнее конечно найденный `answer` заменить на то что на бэке рендерится - см. http://api.jquery.com/replacewith/

2017-07-12 06:35 UTC, iBublik commented on spec/acceptance/answers/best_answer_spec.rb
> +      within all('div[data-answer-id]').last do
Откуда такая любовь к сложным селекторам? Добавь класс к div-ам с ответами и ищи по нему, проще же читать и писать будет

2017-07-12 06:35 UTC, iBublik commented on spec/acceptance/answers/best_answer_spec.rb
> +        expect(page).to have_content all('div[data-answer-id]').last
Этот ассерт некорректен. within ограничивает область поиска, сейчас мы находимся внутри div'а первого  ответа. Откуда там быть div'у другого ответа? Ну и сама идея неверна - зачем нам проверять что тело первого ответа содержит тело последнего ответа?
У тебя есть список ответов, выбери из него последний, сделай его лучшим, проверь что он стал первым на странице

2017-07-12 06:35 UTC, iBublik commented on spec/acceptance/answers/best_answer_spec.rb
> +      within all('div[data-answer-id]').first do
У тебя есть best_answer - найди его по id и проверь что у него больше нет надписи "Лучший ответ" - это самый правильный способ. Ну и/или проверь ссылку "Сделать лучшим" у него

2017-07-12 06:35 UTC, iBublik commented on spec/models/answer_spec.rb
> +    let!(:best_answer) { answers << create(:answer, best: true) }
Я все равно не понимаю зачем ты в массив ответов пихаешь лучший. В итоге в `best_answer` у тебя массив всех ответов, а не лучший ответ

2017-07-12 06:35 UTC, iBublik commented on spec/models/answer_spec.rb
> +  describe '#select_best' do
Нужен тест с проверкой снятия флага с предыдущего лучшего ответа.

2017-07-13 04:48 UTC, iBublik commented on spec/acceptance/answers/best_answer_spec.rb
> +      within :xpath, "//div[@data-answer-id='#{answers.last.id}']" do
А зачем xpath использовать? css проще читается и тоже умеет по data-атрибутам выбирать

2017-07-13 04:48 UTC, iBublik commented on spec/acceptance/answers/best_answer_spec.rb
> +    scenario 'author tries to select best answer', js: true do
Теперь пропала проверка, что ответ стал первым в списке

2017-07-13 04:48 UTC, iBublik commented on spec/acceptance/answers/best_answer_spec.rb
> +        expect(page).to have_content 'Это лучший ответ!'
Зачем эту проверку дублировать? Есть же отдельный тест на это

2017-07-13 07:19 UTC, Ibadichan commented on spec/acceptance/answers/best_answer_spec.rb
> +        expect(page).to have_content 'Это лучший ответ!'
не уходи плиз

2017-07-13 07:20 UTC, Ibadichan commented on spec/acceptance/answers/best_answer_spec.rb
> +        expect(page).to have_content 'Это лучший ответ!'
щаc я опять отправлю в teachbase

2017-07-13 07:40 UTC, vkurennov approved these changes

2017-07-13 09:28 UTC, merged